language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO="1.7.9"
  - DJANGO="1.8.3"
install:
  - pip install -q Django==$DJANGO
  - pip install pep8
  - pip install coveralls
  - pip install django-easysettings
  - pip install pytz
  - pip install -q -e .
before_script:
  - "pep8 --ignore=E501,E225 password_policies"
script:
  - coverage run tests.py
after_success:
  coveralls
