language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO="1.5.12"
  - DJANGO="1.6.11"
  - DJANGO="1.7.9"
  - DJANGO="1.8.2"
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="1.7.9"
    - python: "2.6"
      env: DJANGO="1.8.2"
install:
  - pip install -q Django==$DJANGO
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install importlib; fi
  - pip install pep8
  - pip install coveralls
  - pip install django-easysettings
  - pip install -q -e .
before_script:
  - "pep8 --ignore=E501,E225 password_policies"
script:
  - coverage run tests.py
after_success:
  coveralls
